# Generated by Django 3.2 on 2022-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujamaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
